//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitment_Main.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityId { get; set; }
        public string ActivityType { get; set; }
        public string Activity1 { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string ActivityRemark { get; set; }
        public Nullable<bool> ActivityComplete { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
