//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitment_Main.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Activities = new HashSet<Activity>();
            this.CandidateExams = new HashSet<CandidateExam>();
        }
    
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public Nullable<System.DateTime> CandidateDOB { get; set; }
        public string CandidateSkill { get; set; }
        public string CandidateResume { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.Guid> LastUpdateBy { get; set; }
        public string CandidatePhone { get; set; }
        public string CandidateEmail { get; set; }
        public string CandidatePhone2 { get; set; }
        public string CandidateLocation { get; set; }
        public string CandidateLastJobChange { get; set; }
        public string CandidateOffers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExam> CandidateExams { get; set; }
    }
}
