//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitment_Main.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string FeedbackRemarks { get; set; }
    }
}
