//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitment_Main.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.CandidateExams = new HashSet<CandidateExam>();
        }
    
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public Nullable<bool> JobStatus { get; set; }
        public Nullable<int> JobCount { get; set; }
        public Nullable<System.DateTime> JobTargetDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExam> CandidateExams { get; set; }
    }
}
