//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitment_Main.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMapping
    {
        public int UserMappingId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
