//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessPermission
    {
        public int Id { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<bool> IsAdd { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> IsExport { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
