//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateExam
    {
        public int CandidateExamId { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ExamAnswers { get; set; }
        public Nullable<System.Guid> CandidateExamLinkId { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Job Job { get; set; }
    }
}
