//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTestRecord
    {
        public int CandidateScoreId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public string TestName { get; set; }
        public string TestLink { get; set; }
        public string TestStatus { get; set; }
        public string TestScore { get; set; }
    }
}
