//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateUpload
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Age { get; set; }
        public string Qualification { get; set; }
        public string Location { get; set; }
        public string Company { get; set; }
        public string Project { get; set; }
        public string Technology { get; set; }
        public string Achievement { get; set; }
    }
}
