//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Activities = new HashSet<Activity>();
            this.CandidateExams = new HashSet<CandidateExam>();
            this.CandidatesResumes = new HashSet<CandidatesResume>();
            this.Interviews = new HashSet<Interview>();
            this.ClientCandidateMappings = new HashSet<ClientCandidateMapping>();
            this.MCallerDatas = new HashSet<MCallerData>();
        }
    
        public int CandidateId { get; set; }
        public string CandidateName { get; set; }
        public Nullable<System.DateTime> CandidateDOB { get; set; }
        public string CandidateSkill { get; set; }
        public string CandidateExperience { get; set; }
        public string CandidateResume { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.Guid> LastUpdateBy { get; set; }
        public string CandidatePhone { get; set; }
        public string CandidateEmail { get; set; }
        public string CandidatePhone2 { get; set; }
        public string CandidateLocation { get; set; }
        public string CandidateLastJobChange { get; set; }
        public string SkypeId { get; set; }
        public Nullable<decimal> CurrentCTC { get; set; }
        public Nullable<decimal> ExpectedCTC { get; set; }
        public Nullable<bool> BuyoutOption { get; set; }
        public string Education { get; set; }
        public Nullable<decimal> OffersInHand { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public string ClientDesignation { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Relevant_Exp { get; set; }
        public string Preferred_Location { get; set; }
        public string Last_Job_change_reason { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CurrentOrganisation { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string CandidateVideo { get; set; }
        public string PreviousDesignation { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExam> CandidateExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidatesResume> CandidatesResumes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCandidateMapping> ClientCandidateMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCallerData> MCallerDatas { get; set; }
    }
}
