//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTestURL
    {
        public int CandTestURLId { get; set; }
        public int CandId { get; set; }
        public System.Guid TestURLID { get; set; }
        public bool Status { get; set; }
    }
}
