//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTestResult
    {
        public int ID { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> CandidateAnswerId { get; set; }
        public Nullable<bool> IsMulti { get; set; }
        public string TestName { get; set; }
        public Nullable<int> TestGroupId { get; set; }
        public string TestLink { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public string AssignBy { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
    }
}
