//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.ClientCandidateMappings = new HashSet<ClientCandidateMapping>();
            this.Jobs = new HashSet<Job>();
            this.MCallerDatas = new HashSet<MCallerData>();
            this.UserMappings = new HashSet<UserMapping>();
        }
    
        public int ClientId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string ClientName { get; set; }
        public string ClientAddress { get; set; }
        public string ClientWWW { get; set; }
        public string ClientGST { get; set; }
        public string ClientPhone { get; set; }
        public string ClientEmail { get; set; }
        public string Password { get; set; }
        public string ClientMobile { get; set; }
        public Nullable<bool> ClientStatus { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.Guid> LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string Contact_Person { get; set; }
        public string Client_PAN_No { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ClientCity { get; set; }
        public Nullable<int> ClientCountryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCandidateMapping> ClientCandidateMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCallerData> MCallerDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMapping> UserMappings { get; set; }
    }
}
