//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamId { get; set; }
        public string ExamName { get; set; }
        public Nullable<bool> ExamStatus { get; set; }
        public string ExamSkill { get; set; }
        public string ExamQuestions { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.Guid> LastUpdateBy { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
