//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewQuestionsTime
    {
        public int Id { get; set; }
        public Nullable<int> InterviewId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<double> QuestionTime { get; set; }
        public Nullable<bool> IsAnswerCorrect { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Interview Interview { get; set; }
        public virtual Question Question { get; set; }
    }
}
