//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewEmotion
    {
        public int Id { get; set; }
        public Nullable<int> InterviewId { get; set; }
        public Nullable<double> EmotionTime { get; set; }
        public string EmotionName { get; set; }
        public Nullable<double> EmotionScore { get; set; }
    
        public virtual Interview Interview { get; set; }
    }
}
