//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Activities = new HashSet<Activity>();
            this.CandidateExams = new HashSet<CandidateExam>();
        }
    
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public Nullable<bool> JobStatus { get; set; }
        public Nullable<int> JobCount { get; set; }
        public Nullable<System.DateTime> JobTargetDate { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<decimal> Years_of_Exp { get; set; }
        public string Location { get; set; }
        public string Contact_Person { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateExam> CandidateExams { get; set; }
        public virtual Client Client { get; set; }
    }
}
