//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCallerData
    {
        public int Id { get; set; }
        public string CallDuration { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string CallType { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string NextAction { get; set; }
        public string SendSMSMessage { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
