//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vrecruit.DataBase.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int Id { get; set; }
        public string TestName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> QueId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> Testtime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual QuestionGroup QuestionGroup { get; set; }
    }
}
